import { defineStore } from "pinia";

export const useMeetingStore = defineStore("meetingStore", {
  state: () => ({
    meetings: [
      {
        officeId: "1",
        roomId: "1",
        roomName: "Apollo Room",
        roomCapacity: 50,
        participantCount: 40,
        tanggalRapat: "2024-08-01",
        waktuMulai: "09:00",
        waktuSelesai: "11:00",
        autoChecked: { snackPagi: true, makanSiang: false, snackSore: false },
        totalNominal: 800000,
        snackPagiCount: 40,
        makanSiangCount: 0,
        snackSoreCount: 0,
      },
      {
        officeId: "2",
        roomId: "2",
        roomName: "Zenith Hall",
        roomCapacity: 30,
        participantCount: 20,
        tanggalRapat: "2024-08-02",
        waktuMulai: "13:00",
        waktuSelesai: "15:00",
        autoChecked: { snackPagi: false, makanSiang: true, snackSore: false },
        totalNominal: 600000,
        snackPagiCount: 0,
        makanSiangCount: 20,
        snackSoreCount: 0,
      },
      {
        officeId: "3",
        roomId: "3",
        roomName: "Nebula Suite",
        roomCapacity: 40,
        participantCount: 35,
        tanggalRapat: "2024-08-03",
        waktuMulai: "10:00",
        waktuSelesai: "12:00",
        autoChecked: { snackPagi: true, makanSiang: false, snackSore: false },
        totalNominal: 700000,
        snackPagiCount: 35,
        makanSiangCount: 0,
        snackSoreCount: 0,
      },
      {
        officeId: "4",
        roomId: "4",
        roomName: "Celestial Lounge",
        roomCapacity: 20,
        participantCount: 15,
        tanggalRapat: "2024-08-04",
        waktuMulai: "14:00",
        waktuSelesai: "16:00",
        autoChecked: { snackPagi: false, makanSiang: true, snackSore: false },
        totalNominal: 450000,
        snackPagiCount: 0,
        makanSiangCount: 15,
        snackSoreCount: 0,
      },
      {
        officeId: "5",
        roomId: "5",
        roomName: "Nova Space",
        roomCapacity: 60,
        participantCount: 50,
        tanggalRapat: "2024-08-05",
        waktuMulai: "11:00",
        waktuSelesai: "13:00",
        autoChecked: { snackPagi: true, makanSiang: true, snackSore: false },
        totalNominal: 1500000,
        snackPagiCount: 50,
        makanSiangCount: 50,
        snackSoreCount: 0,
      },
      {
        officeId: "6",
        roomId: "6",
        roomName: "Eclipse Room",
        roomCapacity: 25,
        participantCount: 20,
        tanggalRapat: "2024-08-06",
        waktuMulai: "15:00",
        waktuSelesai: "17:00",
        autoChecked: { snackPagi: false, makanSiang: true, snackSore: true },
        totalNominal: 900000,
        snackPagiCount: 0,
        makanSiangCount: 20,
        snackSoreCount: 20,
      },
      {
        officeId: "7",
        roomId: "7",
        roomName: "Lunar Center",
        roomCapacity: 65,
        participantCount: 53,
        tanggalRapat: "2024-08-06",
        waktuMulai: "15:00",
        waktuSelesai: "17:00",
        autoChecked: { snackPagi: false, makanSiang: true, snackSore: true },
        totalNominal: 900000,
        snackPagiCount: 0,
        makanSiangCount: 20,
        snackSoreCount: 20,
      },
      {
        officeId: "8",
        roomId: "8",
        roomName: "Galaxy Lounge",
        roomCapacity: 125,
        participantCount: 89,
        tanggalRapat: "2024-08-06",
        waktuMulai: "15:00",
        waktuSelesai: "17:00",
        autoChecked: { snackPagi: false, makanSiang: true, snackSore: true },
        totalNominal: 900000,
        snackPagiCount: 0,
        makanSiangCount: 20,
        snackSoreCount: 20,
      },
    ],
  }),
  actions: {
    saveMeetingData(meetingData) {
      this.meetings.push(meetingData);
    },
  },
});
